
AWSTemplateFormatVersion: 2019-03-02
Description: Desplegar servidor desde template de repositorio GitHub.

Mappings:
  RegionMap:
    us-east-1:
      UbuntuAmi: "ami-0ac019f4fcb7cb7e6" #Ubuntu 18.04
      RegionAlias: "Virginia"

Resources:
    Ec2InstanceAirflow:
        Type: AWS::EC2::Instance
        DeletionPolicy: Delete
        Properties:
            InstanceInitiatedShutdownBehavior: terminate
            SubnetId: subnet-0b2f42607453dca80
            InstanceType: "t2.micro"
            ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region" , UbuntuAmi ]
            SecurityGroupIds:
                - "sg-0c88352e8cc7494c7"
            KeyName: "fps-keypair-desarrollo"
            Tags:
            - Key: Name
              Value: "ec2-workshop-codepipeline"
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    echo " ####################  apt install"
                    apt-get update -y
                    apt install awscli -y
